language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/simonjbeaumont/ocaml-travis-coveralls/master/travis-coveralls.sh
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y supercollider
script: bash -ex .travis-opam.sh && if dpkg --compare-versions $OCAML_VERSION ge 4.02; then bash -ex travis-coveralls.sh; fi
env:
  global:
    - PACKAGE=osc
  matrix:
    - OCAML_VERSION=4.01
    - OCAML_VERSION=4.01 DEPOPTS=lwt
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.02 DEPOPTS=lwt
