language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y supercollider xvfb
script:
  - bash -ex .travis-opam.sh
env:
  global:
    - secure: ZZN6Lsym/o3tQFcQZLntcUr6YVH1X8S1NEfceGt/Fuk7x2LHiWoiOqDwLKNAvTeWR7sjrOpU03M8wcjA9AvzgEfrLC0H98mUDwXaOGOmYRl9Dxkvzz+Zwac70kA0jK4ecBNR2wuRblz/2fsezS4fjjNKax7BqDh1LzGjwp1areU=
  matrix:
    - OCAML_VERSION=4.02 PACKAGE=osc
    - OCAML_VERSION=4.03 PACKAGE=osc
    - OCAML_VERSION=4.04 PACKAGE=osc
    - OCAML_VERSION=4.05 PACKAGE=osc
    - OCAML_VERSION=4.06 PACKAGE=osc
    - OCAML_VERSION=4.07 PACKAGE=osc
    - OCAML_VERSION=4.07 PACKAGE=osc-async
    - OCAML_VERSION=4.07 PACKAGE=osc-lwt
    - OCAML_VERSION=4.07 PACKAGE=osc-unix
